project:
  type: website

website:
  title: "Cedric Martinez"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cmrtnz
      - icon: LinkedIn
        href: https://www.linkedin.com/in/cedric-martinez-7a87321b2/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

